/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackgroundSettings {
  'transparency' : bigint,
  'fadeDuration' : bigint,
  'animationIntensity' : bigint,
  'randomizationEnabled' : boolean,
}
export type ExternalBlob = Uint8Array;
export type Listener = Principal;
export interface Playlist { 'id' : string, 'tracks' : Array<TrackRecord> }
export interface Track {
  'id' : string,
  'url' : ExternalBlob,
  'title' : string,
  'duration' : bigint,
  'album' : [] | [string],
  'artist' : string,
  'uploadDate' : bigint,
}
export interface TrackRecord {
  'title' : string,
  'duration' : bigint,
  'album' : [] | [string],
  'audioFile' : ExternalBlob,
  'playCount' : bigint,
  'artist' : string,
}
export interface TrackUpdate {
  'title' : string,
  'duration' : bigint,
  'album' : [] | [string],
  'artist' : string,
}
export interface UploadProgress {
  'isError' : boolean,
  'total' : bigint,
  'uploaded' : bigint,
  'isComplete' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMediaTrack' : ActorMethod<
    [string, string, [] | [string], bigint, ExternalBlob],
    Track
  >,
  'addPlaylist' : ActorMethod<[string, Array<TrackRecord>], Playlist>,
  'addTrackToPlaylist' : ActorMethod<[string, string], Playlist>,
  'addTracksToPlaylist' : ActorMethod<[string, Array<string>], Playlist>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEmptyPlaylist' : ActorMethod<[string], Playlist>,
  'createPlaylistFromLibrary' : ActorMethod<[string, Array<string>], Playlist>,
  'deleteBackgroundGif' : ActorMethod<[string], undefined>,
  'deleteTrack' : ActorMethod<[string], undefined>,
  'getBackgroundGifs' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'getBackgroundSettings' : ActorMethod<[], BackgroundSettings>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFilteredPlaylists' : ActorMethod<[string], Array<Playlist>>,
  'getListenerCount' : ActorMethod<[], bigint>,
  'getMediaLibrary' : ActorMethod<[], Array<[string, Track]>>,
  'getMediaTrack' : ActorMethod<[string], [] | [Track]>,
  'getPlaylists' : ActorMethod<[], Array<Playlist>>,
  'getPlaylistsReverse' : ActorMethod<[], Array<Playlist>>,
  'getSortedMediaLibrary' : ActorMethod<[], Array<Track>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementPlayCount' : ActorMethod<[string, string], undefined>,
  'initializeDefaultGifs' : ActorMethod<
    [Array<[string, ExternalBlob]>],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMediaLibrary' : ActorMethod<[string], Array<Track>>,
  'startListenerSession' : ActorMethod<[], Listener>,
  'stopListenerSession' : ActorMethod<[Listener], undefined>,
  'storeUploadProgress' : ActorMethod<[UploadProgress], UploadProgress>,
  'updateBackgroundSettings' : ActorMethod<[BackgroundSettings], undefined>,
  'updateTrackMetadata' : ActorMethod<
    [string, string, string, [] | [string], bigint],
    Track
  >,
  'updateTracksMetadata' : ActorMethod<
    [Array<[string, TrackUpdate]>],
    Array<Track>
  >,
  'uploadBackgroundGif' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];