/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Track = IDL.Record({
  'id' : IDL.Text,
  'url' : ExternalBlob,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Opt(IDL.Text),
  'artist' : IDL.Text,
  'uploadDate' : IDL.Int,
});
export const TrackRecord = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Opt(IDL.Text),
  'audioFile' : ExternalBlob,
  'playCount' : IDL.Nat,
  'artist' : IDL.Text,
});
export const Playlist = IDL.Record({
  'id' : IDL.Text,
  'tracks' : IDL.Vec(TrackRecord),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BackgroundSettings = IDL.Record({
  'transparency' : IDL.Nat,
  'fadeDuration' : IDL.Nat,
  'animationIntensity' : IDL.Nat,
  'randomizationEnabled' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Listener = IDL.Principal;
export const UploadProgress = IDL.Record({
  'isError' : IDL.Bool,
  'total' : IDL.Nat,
  'uploaded' : IDL.Nat,
  'isComplete' : IDL.Bool,
});
export const TrackUpdate = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Opt(IDL.Text),
  'artist' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMediaTrack' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, ExternalBlob],
      [Track],
      [],
    ),
  'addPlaylist' : IDL.Func([IDL.Text, IDL.Vec(TrackRecord)], [Playlist], []),
  'addTrackToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [Playlist], []),
  'addTracksToPlaylist' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [Playlist],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEmptyPlaylist' : IDL.Func([IDL.Text], [Playlist], []),
  'createPlaylistFromLibrary' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [Playlist],
      [],
    ),
  'deleteBackgroundGif' : IDL.Func([IDL.Text], [], []),
  'deleteTrack' : IDL.Func([IDL.Text], [], []),
  'getBackgroundGifs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      ['query'],
    ),
  'getBackgroundSettings' : IDL.Func([], [BackgroundSettings], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFilteredPlaylists' : IDL.Func([IDL.Text], [IDL.Vec(Playlist)], ['query']),
  'getListenerCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMediaLibrary' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Track))],
      ['query'],
    ),
  'getMediaTrack' : IDL.Func([IDL.Text], [IDL.Opt(Track)], ['query']),
  'getPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'getPlaylistsReverse' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'getSortedMediaLibrary' : IDL.Func([], [IDL.Vec(Track)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementPlayCount' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'initializeDefaultGifs' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
      [],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchMediaLibrary' : IDL.Func([IDL.Text], [IDL.Vec(Track)], ['query']),
  'startListenerSession' : IDL.Func([], [Listener], []),
  'stopListenerSession' : IDL.Func([Listener], [], []),
  'storeUploadProgress' : IDL.Func([UploadProgress], [UploadProgress], []),
  'updateBackgroundSettings' : IDL.Func([BackgroundSettings], [], []),
  'updateTrackMetadata' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
      [Track],
      [],
    ),
  'updateTracksMetadata' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, TrackUpdate))],
      [IDL.Vec(Track)],
      [],
    ),
  'uploadBackgroundGif' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Track = IDL.Record({
    'id' : IDL.Text,
    'url' : ExternalBlob,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Opt(IDL.Text),
    'artist' : IDL.Text,
    'uploadDate' : IDL.Int,
  });
  const TrackRecord = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Opt(IDL.Text),
    'audioFile' : ExternalBlob,
    'playCount' : IDL.Nat,
    'artist' : IDL.Text,
  });
  const Playlist = IDL.Record({
    'id' : IDL.Text,
    'tracks' : IDL.Vec(TrackRecord),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BackgroundSettings = IDL.Record({
    'transparency' : IDL.Nat,
    'fadeDuration' : IDL.Nat,
    'animationIntensity' : IDL.Nat,
    'randomizationEnabled' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Listener = IDL.Principal;
  const UploadProgress = IDL.Record({
    'isError' : IDL.Bool,
    'total' : IDL.Nat,
    'uploaded' : IDL.Nat,
    'isComplete' : IDL.Bool,
  });
  const TrackUpdate = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Opt(IDL.Text),
    'artist' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMediaTrack' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, ExternalBlob],
        [Track],
        [],
      ),
    'addPlaylist' : IDL.Func([IDL.Text, IDL.Vec(TrackRecord)], [Playlist], []),
    'addTrackToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [Playlist], []),
    'addTracksToPlaylist' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [Playlist],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEmptyPlaylist' : IDL.Func([IDL.Text], [Playlist], []),
    'createPlaylistFromLibrary' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [Playlist],
        [],
      ),
    'deleteBackgroundGif' : IDL.Func([IDL.Text], [], []),
    'deleteTrack' : IDL.Func([IDL.Text], [], []),
    'getBackgroundGifs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        ['query'],
      ),
    'getBackgroundSettings' : IDL.Func([], [BackgroundSettings], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFilteredPlaylists' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Playlist)],
        ['query'],
      ),
    'getListenerCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMediaLibrary' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Track))],
        ['query'],
      ),
    'getMediaTrack' : IDL.Func([IDL.Text], [IDL.Opt(Track)], ['query']),
    'getPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'getPlaylistsReverse' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'getSortedMediaLibrary' : IDL.Func([], [IDL.Vec(Track)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementPlayCount' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'initializeDefaultGifs' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob))],
        [],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchMediaLibrary' : IDL.Func([IDL.Text], [IDL.Vec(Track)], ['query']),
    'startListenerSession' : IDL.Func([], [Listener], []),
    'stopListenerSession' : IDL.Func([Listener], [], []),
    'storeUploadProgress' : IDL.Func([UploadProgress], [UploadProgress], []),
    'updateBackgroundSettings' : IDL.Func([BackgroundSettings], [], []),
    'updateTrackMetadata' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
        [Track],
        [],
      ),
    'updateTracksMetadata' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, TrackUpdate))],
        [IDL.Vec(Track)],
        [],
      ),
    'uploadBackgroundGif' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };