/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TrackRecord {
    title: string;
    duration: bigint;
    album?: string;
    audioFile: ExternalBlob;
    playCount: bigint;
    artist: string;
}
export type Listener = Principal;
export interface BackgroundSettings {
    transparency: bigint;
    fadeDuration: bigint;
    animationIntensity: bigint;
    randomizationEnabled: boolean;
}
export interface Track {
    url: ExternalBlob;
    title: string;
    duration: bigint;
    album?: string;
    artist: string;
    uploadDate: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Playlist {
    id: string;
    tracks: Array<TrackRecord>;
}
export interface TrackUpdate {
    title: string;
    duration: bigint;
    album?: string;
    trackId: string;
    artist: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UploadProgress {
    isError: boolean;
    total: bigint;
    uploaded: bigint;
    isComplete: boolean;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMediaTrack(title: string, artist: string, album: string | null, duration: bigint, url: ExternalBlob): Promise<Track>;
    addPlaylist(newPlaylistId: string, tracks: Array<TrackRecord>): Promise<Playlist>;
    addTrackToPlaylist(playlistId: string, trackId: string): Promise<Playlist>;
    addTracksToPlaylist(playlistId: string, trackIds: Array<string>): Promise<Playlist>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEmptyPlaylist(playlistId: string): Promise<Playlist>;
    createPlaylistFromLibrary(playlistId: string, trackIds: Array<string>): Promise<Playlist>;
    deleteBackgroundGif(gifId: string): Promise<void>;
    deleteTrack(trackId: string): Promise<void>;
    getBackgroundGifs(): Promise<Array<[string, ExternalBlob]>>;
    getBackgroundSettings(): Promise<BackgroundSettings>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFilteredPlaylists(playlistId: string): Promise<Array<Playlist>>;
    getListenerCount(): Promise<bigint>;
    getMediaLibrary(): Promise<Array<[string, Track]>>;
    getMediaTrack(trackId: string): Promise<Track | null>;
    getPlaylists(): Promise<Array<Playlist>>;
    getPlaylistsReverse(): Promise<Array<Playlist>>;
    getSortedMediaLibrary(): Promise<Array<Track>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    incrementPlayCount(playlistId: string, trackTitle: string): Promise<void>;
    initializeDefaultGifs(defaultGifs: Array<[string, ExternalBlob]>): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchMediaLibrary(term: string): Promise<Array<Track>>;
    startListenerSession(): Promise<Listener>;
    stopListenerSession(listener: Listener): Promise<void>;
    storeUploadProgress(progress: UploadProgress): Promise<UploadProgress>;
    updateBackgroundSettings(settings: BackgroundSettings): Promise<void>;
    updateTrackMetadata(trackId: string, title: string, artist: string, album: string | null, duration: bigint): Promise<Track>;
    updateTracksMetadata(batch: Array<TrackUpdate>): Promise<Array<Track>>;
    uploadBackgroundGif(gifId: string, gifFile: ExternalBlob): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, Playlist as _Playlist, Track as _Track, TrackRecord as _TrackRecord, TrackUpdate as _TrackUpdate, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMediaTrack(arg0: string, arg1: string, arg2: string | null, arg3: bigint, arg4: ExternalBlob): Promise<Track> {
        if (this.processError) {
            try {
                const result = await this.actor.addMediaTrack(arg0, arg1, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg2), arg3, await to_candid_ExternalBlob_n9(this.uploadFile, this.downloadFile, arg4));
                return from_candid_Track_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMediaTrack(arg0, arg1, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg2), arg3, await to_candid_ExternalBlob_n9(this.uploadFile, this.downloadFile, arg4));
            return from_candid_Track_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async addPlaylist(arg0: string, arg1: Array<TrackRecord>): Promise<Playlist> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlaylist(arg0, await to_candid_vec_n14(this.uploadFile, this.downloadFile, arg1));
                return from_candid_Playlist_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlaylist(arg0, await to_candid_vec_n14(this.uploadFile, this.downloadFile, arg1));
            return from_candid_Playlist_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async addTrackToPlaylist(arg0: string, arg1: string): Promise<Playlist> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrackToPlaylist(arg0, arg1);
                return from_candid_Playlist_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrackToPlaylist(arg0, arg1);
            return from_candid_Playlist_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async addTracksToPlaylist(arg0: string, arg1: Array<string>): Promise<Playlist> {
        if (this.processError) {
            try {
                const result = await this.actor.addTracksToPlaylist(arg0, arg1);
                return from_candid_Playlist_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTracksToPlaylist(arg0, arg1);
            return from_candid_Playlist_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async createEmptyPlaylist(arg0: string): Promise<Playlist> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmptyPlaylist(arg0);
                return from_candid_Playlist_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmptyPlaylist(arg0);
            return from_candid_Playlist_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async createPlaylistFromLibrary(arg0: string, arg1: Array<string>): Promise<Playlist> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlaylistFromLibrary(arg0, arg1);
                return from_candid_Playlist_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlaylistFromLibrary(arg0, arg1);
            return from_candid_Playlist_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async deleteBackgroundGif(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBackgroundGif(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBackgroundGif(arg0);
            return result;
        }
    }
    async deleteTrack(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrack(arg0);
            return result;
        }
    }
    async getBackgroundGifs(): Promise<Array<[string, ExternalBlob]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackgroundGifs();
                return from_candid_vec_n24(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackgroundGifs();
            return from_candid_vec_n24(this.uploadFile, this.downloadFile, result);
        }
    }
    async getBackgroundSettings(): Promise<BackgroundSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackgroundSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackgroundSettings();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getFilteredPlaylists(arg0: string): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredPlaylists(arg0);
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredPlaylists(arg0);
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getListenerCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getListenerCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListenerCount();
            return result;
        }
    }
    async getMediaLibrary(): Promise<Array<[string, Track]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaLibrary();
                return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaLibrary();
            return from_candid_vec_n30(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMediaTrack(arg0: string): Promise<Track | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaTrack(arg0);
                return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaTrack(arg0);
            return from_candid_opt_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPlaylists(): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaylists();
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaylists();
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPlaylistsReverse(): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaylistsReverse();
                return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaylistsReverse();
            return from_candid_vec_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getSortedMediaLibrary(): Promise<Array<Track>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedMediaLibrary();
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedMediaLibrary();
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async incrementPlayCount(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementPlayCount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementPlayCount(arg0, arg1);
            return result;
        }
    }
    async initializeDefaultGifs(arg0: Array<[string, ExternalBlob]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDefaultGifs(await to_candid_vec_n34(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDefaultGifs(await to_candid_vec_n34(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchMediaLibrary(arg0: string): Promise<Array<Track>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchMediaLibrary(arg0);
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchMediaLibrary(arg0);
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async startListenerSession(): Promise<Listener> {
        if (this.processError) {
            try {
                const result = await this.actor.startListenerSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startListenerSession();
            return result;
        }
    }
    async stopListenerSession(arg0: Listener): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.stopListenerSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopListenerSession(arg0);
            return result;
        }
    }
    async storeUploadProgress(arg0: UploadProgress): Promise<UploadProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.storeUploadProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeUploadProgress(arg0);
            return result;
        }
    }
    async updateBackgroundSettings(arg0: BackgroundSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBackgroundSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBackgroundSettings(arg0);
            return result;
        }
    }
    async updateTrackMetadata(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: bigint): Promise<Track> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrackMetadata(arg0, arg1, arg2, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg3), arg4);
                return from_candid_Track_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrackMetadata(arg0, arg1, arg2, to_candid_opt_n8(this.uploadFile, this.downloadFile, arg3), arg4);
            return from_candid_Track_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async updateTracksMetadata(arg0: Array<TrackUpdate>): Promise<Array<Track>> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTracksMetadata(to_candid_vec_n36(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTracksMetadata(to_candid_vec_n36(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n33(this.uploadFile, this.downloadFile, result);
        }
    }
    async uploadBackgroundGif(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadBackgroundGif(arg0, await to_candid_ExternalBlob_n9(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadBackgroundGif(arg0, await to_candid_ExternalBlob_n9(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_Playlist_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Playlist): Promise<Playlist> {
    return await from_candid_record_n18(uploadFile, downloadFile, value);
}
async function from_candid_TrackRecord_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrackRecord): Promise<TrackRecord> {
    return await from_candid_record_n21(uploadFile, downloadFile, value);
}
async function from_candid_Track_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Track): Promise<Track> {
    return await from_candid_record_n11(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Track]): Promise<Track | null> {
    return value.length === 0 ? null : await from_candid_Track_n10(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: _ExternalBlob;
    title: string;
    duration: bigint;
    album: [] | [string];
    artist: string;
    uploadDate: string;
}): Promise<{
    url: ExternalBlob;
    title: string;
    duration: bigint;
    album?: string;
    artist: string;
    uploadDate: string;
}> {
    return {
        url: await from_candid_ExternalBlob_n12(uploadFile, downloadFile, value.url),
        title: value.title,
        duration: value.duration,
        album: record_opt_to_undefined(from_candid_opt_n13(uploadFile, downloadFile, value.album)),
        artist: value.artist,
        uploadDate: value.uploadDate
    };
}
async function from_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    tracks: Array<_TrackRecord>;
}): Promise<{
    id: string;
    tracks: Array<TrackRecord>;
}> {
    return {
        id: value.id,
        tracks: await from_candid_vec_n19(uploadFile, downloadFile, value.tracks)
    };
}
async function from_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: bigint;
    album: [] | [string];
    audioFile: _ExternalBlob;
    playCount: bigint;
    artist: string;
}): Promise<{
    title: string;
    duration: bigint;
    album?: string;
    audioFile: ExternalBlob;
    playCount: bigint;
    artist: string;
}> {
    return {
        title: value.title,
        duration: value.duration,
        album: record_opt_to_undefined(from_candid_opt_n13(uploadFile, downloadFile, value.album)),
        audioFile: await from_candid_ExternalBlob_n12(uploadFile, downloadFile, value.audioFile),
        playCount: value.playCount,
        artist: value.artist
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ExternalBlob]): Promise<[string, ExternalBlob]> {
    return [
        value[0],
        await from_candid_ExternalBlob_n12(uploadFile, downloadFile, value[1])
    ];
}
async function from_candid_tuple_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Track]): Promise<[string, Track]> {
    return [
        value[0],
        await from_candid_Track_n10(uploadFile, downloadFile, value[1])
    ];
}
function from_candid_variant_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrackRecord>): Promise<Array<TrackRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TrackRecord_n20(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ExternalBlob]>): Promise<Array<[string, ExternalBlob]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n25(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Playlist>): Promise<Array<Playlist>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Playlist_n17(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Track]>): Promise<Array<[string, Track]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n31(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Track>): Promise<Array<Track>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Track_n10(uploadFile, downloadFile, x)));
}
async function to_candid_ExternalBlob_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
async function to_candid_TrackRecord_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrackRecord): Promise<_TrackRecord> {
    return await to_candid_record_n16(uploadFile, downloadFile, value);
}
function to_candid_TrackUpdate_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrackUpdate): _TrackUpdate {
    return to_candid_record_n38(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_opt_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: bigint;
    album?: string;
    audioFile: ExternalBlob;
    playCount: bigint;
    artist: string;
}): Promise<{
    title: string;
    duration: bigint;
    album: [] | [string];
    audioFile: _ExternalBlob;
    playCount: bigint;
    artist: string;
}> {
    return {
        title: value.title,
        duration: value.duration,
        album: value.album ? candid_some(value.album) : candid_none(),
        audioFile: await to_candid_ExternalBlob_n9(uploadFile, downloadFile, value.audioFile),
        playCount: value.playCount,
        artist: value.artist
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    duration: bigint;
    album?: string;
    trackId: string;
    artist: string;
}): {
    title: string;
    duration: bigint;
    album: [] | [string];
    trackId: string;
    artist: string;
} {
    return {
        title: value.title,
        duration: value.duration,
        album: value.album ? candid_some(value.album) : candid_none(),
        trackId: value.trackId,
        artist: value.artist
    };
}
async function to_candid_tuple_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, ExternalBlob]): Promise<[string, _ExternalBlob]> {
    return [
        value[0],
        await to_candid_ExternalBlob_n9(uploadFile, downloadFile, value[1])
    ];
}
function to_candid_variant_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TrackRecord>): Promise<Array<_TrackRecord>> {
    return await Promise.all(value.map(async (x)=>await to_candid_TrackRecord_n15(uploadFile, downloadFile, x)));
}
async function to_candid_vec_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, ExternalBlob]>): Promise<Array<[string, _ExternalBlob]>> {
    return await Promise.all(value.map(async (x)=>await to_candid_tuple_n35(uploadFile, downloadFile, x)));
}
function to_candid_vec_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TrackUpdate>): Array<_TrackUpdate> {
    return value.map((x)=>to_candid_TrackUpdate_n37(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
